name: moor_shared
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bloc: ^6.0.3
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.5
  intl: ^0.16.0
  isolated_worker: ^0.0.1+2
  moor: ^3.1.0
  path: ^1.6.4
  path_provider: ^1.3.0
  rxdart: ^0.22.2
  sqlite3_flutter_libs: ^0.2.0
  undo: ^1.3.0+1

dev_dependencies:
  build_runner: ^1.6.7
  build_web_compilers: ^2.3.0
  flutter_test:
    sdk: flutter
  moor_generator: ^3.1.0

flutter:
  uses-material-design: true
